<?php
/**
 * Created by PhpStorm.
 * User: Stomick
 * Date: 19.07.2018
 * Time: 17:06
 */

namespace app\models\statistic;


use app\models\Games;
use app\models\GameStatistic;
use app\models\SubTournaments;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class CommandPosInTour extends ActiveRecord
{
    public static function tableName()
    {
        return 'com_pos_in_tour';
    }

    public function update($runValidation = true, $attributeNames = null)
    {
        $vin = 0;
        $draw = 0;
        $lose = 0;
        foreach (GameStatistic::find()->where(['command_id' => $this->command_id, 'sub_tournament_id' => $this->sub_tournament_id])->all() as $k => $goals) {
            $dis = $goals->scored - $goals->missed;
            if ($dis > 0) {
                $vin++;
            } elseif ($dis == 0) {
                $draw++;
            } else {
                $lose++;
            }
            $this->win = $vin;
            $this->draw = $draw;
            $this->lose = $lose;
        }
        return parent::update($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}