<?php
/**
 * Created by PhpStorm.
 * User: Stomick
 * Date: 19.07.2018
 * Time: 17:06
 */

namespace app\models\statistic;


use app\models\Games;
use app\models\GameStatistic;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class EventsInGame extends ActiveRecord
{
    public static function tableName()
    {
        return 'events';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    public function delete()
    {
        /*
        $vin = 0;
        $draw = 0;
        $lose = 0;
        foreach (GameStatistic::find()->where(['game_id'=> $this->game_id ])->all() as $k => $goals) {
            $dis = $goals->scored - $goals->missed;
            if ($dis > 0) {
                $vin++;
            } elseif ($dis == 0) {
                $draw++;
            } else {
                $lose++;
            }
            $goals->win = $vin;
            $goals->draw = $draw;
            $goals->lose = $lose;
            $goals->update();
        }
        */
        return parent::delete(); // TODO: Change the autogenerated stub
    }
    public function afterSave($insert, $changedAttributes)
    {
        if($this->type_event_id == 14){
            if($g = Games::findOne($this->game_id)){
                $g->the_end = 1;
                $g->update();
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
    public function beforeDelete()
    {
        if($this->type_event_id == 6){
            if($g = Games::findOne($this->game_id)){
                $g->the_end = 0;
                $g->update();
            }
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}