<?php
/**
 * Created by PhpStorm.
 * User: Stomick
 * Date: 19.07.2018
 * Time: 17:06
 */

namespace app\models\statistic;


use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class PlayersToGame extends ActiveRecord
{
    public static function tableName()
    {
        return 'pl_to_game';
    }

    public function beforeSave($insert)
    {
        if($cm = PlayersInCommand::find()->where(['player_id' => $this->player_id])->one()) {
            $this->command_id = $cm->command_id;
            }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}