<?php
/**
 * Created by PhpStorm.
 * User: Stomick
 * Date: 18.07.2018
 * Time: 15:25
 */

namespace app\controllers;

use app\components\CompAuthG4U;
use app\models\Leagues;
use app\models\admin\Players;
use app\models\LoginForm;
use app\models\News;
use app\models\SignupForm;
use app\models\User;
use yii\filters\auth\CompositeAuth;
use app\components\HttpBearerAuthG4U;
use app\components\AuthG4U;
use yii\filters\auth\QueryParamAuth;
use yii\filters\ContentNegotiator;

use yii\rest\Controller;
use yii\web\Response;

class LeaguesController extends Controller
{
    private $answer;
    private $error = false;
    private $body;
    private $getId;
    private $message;
    private $user;
    private $accept;
    /**
     * {@inheritdoc}
     */

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => CompAuthG4U::className(),
            'authMethods' => [
                HttpBearerAuthG4U::className()
            ],
        ];

        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::className(),
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];

        return $behaviors;
    }
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    public function beforeAction($action)
    {
        $this->accept = \Yii::$app->request->getHeaders()->get('Authorization');
        if (\Yii::$app->request->isPost) {
            if (!$this->body = \Yii::$app->request->getBodyParams()) {
                $this->error = true;
                $this->message = 'empty body';
                return;
            }
        }

        $this->user = User::findIdentityByAccessToken(explode(' ', $this->accept)[1]);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        return ['answer' => $this->answer,'error' => $this->error,'message' => $this->message];
    }

    public function actionIndex(){
        $this->answer = Leagues::find()->select(['leagues_id as id' , 'title' , 'status'])->asArray()->all();
    }
    public function actionSet(){
        $this->user->league_id = intval($this->body['league']);
        return $this->user->update() ? $this->answer = true: $this->error = true;
    }
}
