<?php
/**
 * Created by PhpStorm.
 * User: Stomick
 * Date: 19.07.2018
 * Time: 17:06
 */

namespace app\models;


use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class GamesPhotos extends ActiveRecord
{
    public static function tableName()
    {
        return 'games_photo';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    public function beforeDelete()
    {
        if (file_exists($_SERVER['DOCUMENT_ROOT'].$this->src)) {
            unlink($_SERVER['DOCUMENT_ROOT'] . $this->src);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}